name: RL
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - pip:
      - matplotlib==3.10.7
      - numpy==2.2.6
      - pandas==2.3.3
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - tqdm==4.67.1
      - vitaldb==1.5.8